language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t petorian/docker-react -f Dockerfile.dev .


script:
  - docker run petorian/docker-react npm run test -- --coverage